-- Sample schema for storing cloud resources
CREATE TABLE cloud_resource (
    id NUMBER PRIMARY KEY,
    name VARCHAR2(100),
    type VARCHAR2(50),
    region VARCHAR2(50),
    cpu_utilization NUMBER,
    memory_utilization NUMBER,
    cost_per_hour NUMBER,
    last_updated TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
CREATE TABLE cloud_resources (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    resource_type VARCHAR2(255),
    usage_amount FLOAT,
    cost FLOAT,
    provider VARCHAR2(255),
    region VARCHAR2(255)
);
